import './polyfill-amis'
import ReactDOM from 'react-dom'
import '@fortawesome/fontawesome-free/css/all.css'
import '@fortawesome/fontawesome-free/css/v4-shims.css'
import 'amis/lib/themes/cxd.css'
import 'amis/lib/helper.css'
import 'amis/sdk/iconfont.css'
import 'react-datetime/css/react-datetime.css'
import 'codemirror/lib/codemirror.css'
import 'cropperjs/dist/cropper.css'
import 'video-react/dist/video-react.css'
import './scss/style.scss'
import { EditorComponent } from '@/entry'

ReactDOM.render(<EditorComponent />, document.getElementById('root'))
